name: Publish Prebuilt CI Environment

on:
  push:
    branches: ["main"]

env:
  PKR_VAR_registry: ghcr.io
  PKR_VAR_repository: ghcr.io/${{ github.repository }}
  PKR_VAR_username: ${{ github.actor }}
  PKR_VAR_password: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate dependent package version
        run: |
          echo "packer_version=\"$(curl https://api.github.com/repos/hashicorp/packer/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "terraform_version=\"$(curl https://api.github.com/repos/hashicorp/terraform/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "cfssl_version=\"$(curl https://api.github.com/repos/cloudflare/cfssl/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "nomad_version=\"$(curl https://api.github.com/repos/hashicorp/nomad/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "consul_version=\"$(curl https://api.github.com/repos/hashicorp/consul/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "vault_version=\"$(curl https://api.github.com/repos/hashicorp/vault/releases/latest -s | jq .name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl
          echo "tailscale_version=\"$(curl https://api.github.com/repos/tailscale/tailscale/releases/latest -s | jq .tag_name -r | sed s/v//)\"" >> dependencies.auto.pkrvars.hcl

      - name: Initializes Packer
        run: packer init .

      - name: Validate packer configurations
        run: packer validate -syntax-only .

      - name: Run packer build
        run: |
          packer build -color=false -on-error=abort -only 'docker.base' .
          packer build -color=false -on-error=abort -only 'docker.packer' .
          packer build -color=false -on-error=abort -only 'docker.terraform' .
          packer build -color=false -on-error=abort -only 'docker.provisioner' .
